declare module '@engine';
declare module "@modules";
declare module '@controllers';
declare module '@exceptions';
declare module '@interfaces';
declare module '@middlewares';
declare module '@models';
declare module '@routes';
declare module '@services';
